backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  # - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
  #   label: "Post" # Used in the UI, ie.: "New Post"
  #   folder: "site/content/post" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   fields: # The fields each document in this collection have
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Intro Blurb", name: "description", widget: "text"}
  #     - {label: "Image", name: "image", widget: "image", required: false}
  #     - {label: "MD", name: "md", widget: "markdown"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  # - name: "pages"
  #   label: "Pages"
  #   files:
  #     - file: "site/content/products.md"
  #       label: "Products Page "
  #       name: "products"
  #       fields:
  #         - {label: Title, name: title, widget: string}
  #         - {label: Type, name: type, widget: hidden, default: products}
  #         - {label: Page, name: page, widget: hidden, default: "/products.html"}
  #         - {label: Image, name: image, widget: image}
  #         - {label: Heading, name: heading, widget: string}
  #         - {label: Description, name: description, widget: string}
  #         - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
  #         - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
  #         - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
  #         - {label: Full_image, name: full_image, widget: image}
  #         - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
  - name: "Home EN"
    label: "Home Page (EN)"
    files:
      - file: "site/content/_index.md"
        label: "Home Page (EN)"
        name: "Vince + Trello"
        fields:
          - {label: "Page Title", name: title, widget: string}
          - {label: Type, name: type, widget: hidden}
          - {label: SubType, name: subtype, widget: string}
          - {label: Page, name: page, widget: hidden, default: "/index.html"}
          - {label: Sub title, name: sub_title, widget: string, required: false}          
          - {label: Header, name: headermd, widget: "markdown"}
          - {label: Image header top, name: imageheadertop, widget: string}
          - {label: Image header bottom, name: imageheaderbottom, widget: string}
          - {label: Emoji, name: emoji, widget: list, fields: [{label: Class, name: class, widget: string }, {label: Emoji, name: emoji, widget: string }], required: false}
          - {label: Description, name: description, widget: "markdown"}
          - {label: Features, name: features, widget: list, fields: [{label: Content, name: contentmd, widget: "markdown"},{label: Image, name: image, widget: string} ]}
          - {label: More, name: more, widget: "markdown", required: false}
          - {label: More Description, name: moredescription, widget:"markdown" , required: false}
          - {label: Button Top, name: buttonLinkTop, widget: object, fields: [{label: Label, name: label, widget: string}, {label: Url, name: url, widget: string} ], required: false}
          - {label: Button Bottom, name: buttonLinkBottom, widget: object, fields: [{label: Label, name: label, widget: string}, {label: Url, name: url, widget: string} ], required: false}
          - {label: "Show CTA ?", name: showCTA, widget: boolean }
          - {label: Email subject, name: emailsubject, widget: text, required: false}
  - name: "Home FR"
    label: "Home Page (FR)"
    files:
      - file: "site/content/_index.fr.md"
        label: "Home Page (FR)"
        name: "Vince + Trello"
        fields:
          - {label: "Page Title", name: title, widget: string}
          - {label: Type, name: type, widget: hidden}
          - {label: SubType, name: subtype, widget: string}
          - {label: Page, name: page, widget: hidden, default: "/index.html"}
          - {label: Sub title, name: sub_title, widget: string, required: false}          
          - {label: Header, name: headermd, widget: "markdown"}
          - {label: Image header top, name: imageheadertop, widget: string}
          - {label: Image header bottom, name: imageheaderbottom, widget: string}
          - {label: Emoji, name: emoji, widget: list, fields: [{label: Class, name: class, widget: string }, {label: Emoji, name: emoji, widget: string }], required: false}
          - {label: Description, name: description, widget: "markdown"}
          - {label: Features, name: features, widget: list, fields: [{label: Content, name: contentmd, widget: "markdown"},{label: Image, name: image, widget: string} ]}
          - {label: More, name: more, widget: "markdown", required: false}
          - {label: More Description, name: moredescription, widget:"markdown" , required: false}
          - {label: Button Top, name: buttonLinkTop, widget: object, fields: [{label: Label, name: label, widget: string}, {label: Url, name: url, widget: string} ], required: false}
          - {label: Button Bottom, name: buttonLinkBottom, widget: object, fields: [{label: Label, name: label, widget: string}, {label: Url, name: url, widget: string} ], required: false}
          - {label: "Show CTA ?", name: showCTA, widget: boolean }
          - {label: Email subject, name: emailsubject, widget: text, required: false}
  # - name: "Scrum EN"
  #   label: "Scrum Page (EN)"
  #   files:
  #     - file: "site/content/scrum.md"
  #       label: "Scrum Page (EN)"
  #       name: "Scrum"
  #       fields:
  #         - {label: Title, name: title, widget: string}
  #         - {label: Type, name: type, widget: hidden, default: "vince"}
  #         - {label: SubType, name: subtype, widget: string}
  #         - {label: Page, name: page, widget: hidden, default: "/scrum/index.html"}
  #         - {label: Sub_title, name: sub_title, widget: string, required: false}          
  #         - {label: Header, name: header, widget: list, fields: [{label: Title, name: title, widget: string }]}
  #         - {label: Emoji, name: emoji, widget: list, fields: [{label: Class, name: class, widget: string }, {label: Emoji, name: emoji, widget: string }], required: false}
  #         - {label: Description, name: description, widget: text}
  #         - {label: SubDescription1, name: subdescription1, widget: text, required: false}
  #         - {label: SubDescription2, name: subdescription2, widget: text, required: false}
  #         - {label: Features, name: features, widget: list, fields: [{label: Name, name: name, widget: string}, {label: Title, name: title, widget: string},{label: SubTitle, name: subtitle, widget: string}, {label: ImageName, name: imagename, widget: string} ]}
  #         - {label: More, name: more, widget: text, required: false}
  #         - {label: TrelloButton, name: trelloButton, widget: object, fields: [{label: Label, name: label, widget: string}, {label: Url, name: url, widget: string} ], required: false}
  #         - {label: Infos, name: infos, widget: object, fields: [{label: Title, name: title, widget: string},{label: SubTitle, name: subtitle, widget: text}, {label: Link, name: link, widget: object, fields: [{label: Url, name: url, widget: string}, {label: Label, name: label, widget: string}]}], required: false}
  #         - {label: EmailSubject, name: emailsubject, widget: text, required: false}
  # - name: "Scrum FR"
  #   label: "Scrum Page (FR)"
  #   files:
  #     - file: "site/content/scrum.fr.md"
  #       label: "Scrum Page (FR)"
  #       name: "Scrum"
  #       fields:
  #         - {label: Title, name: title, widget: string}
  #         - {label: Type, name: type, widget: hidden, default: "vince"}
  #         - {label: SubType, name: subtype, widget: string}
  #         - {label: Page, name: page, widget: hidden, default: "/fr/scrum/index.html"}
  #         - {label: Sub_title, name: sub_title, widget: string, required: false}          
  #         - {label: Header, name: header, widget: list, fields: [{label: Title, name: title, widget: string }]}
  #         - {label: Emoji, name: emoji, widget: list, fields: [{label: Class, name: class, widget: string }, {label: Emoji, name: emoji, widget: string }], required: false}
  #         - {label: Description, name: description, widget: text}
  #         - {label: SubDescription1, name: subdescription1, widget: text, required: false}
  #         - {label: SubDescription2, name: subdescription2, widget: text, required: false}
  #         - {label: Features, name: features, widget: list, fields: [{label: Name, name: name, widget: string}, {label: Title, name: title, widget: string},{label: SubTitle, name: subtitle, widget: string}, {label: ImageName, name: imagename, widget: string} ]}
  #         - {label: More, name: more, widget: text, required: false}
  #         - {label: TrelloButton, name: trelloButton, widget: object, fields: [{label: Label, name: label, widget: string}, {label: Url, name: url, widget: string} ], required: false}
  #         - {label: Infos, name: infos, widget: object, fields: [{label: Title, name: title, widget: string},{label: SubTitle, name: subtitle, widget: text}, {label: Link, name: link, widget: object, fields: [{label: Url, name: url, widget: string}, {label: Label, name: label, widget: string}]}], required: false}
  #         - {label: EmailSubject, name: emailsubject, widget: text, required: false}
  
